apiVersion: v1
kind: Pod
metadata:
   name: multi-containers
   labels:
     project: roboshop
     purpose: multi-container-demo
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9