apiVersion: v1
kind: Service 
metadata:
  name: sc-headless-svc
  labels:
     purpose: statefulset
     project: roboshop
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None 
  selector:
    purpose: statefulset # these are pod labels
    project: roboshop
---
apiVersion: v1
kind: Service # we need to create normal service pod to pod communiction
metadata:
  name: sc-normal-svc
  labels:
     purpose: statefulset
     project: roboshop
spec:
  ports:
  - port: 80
    name: web 
  selector:
    purpose: statefulset # these are pod labels
    project: roboshop
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sc-headless
spec:
  selector:
    matchLabels:
    purpose: statefulset 
    project: roboshop  # has to match .spec.template.metadata.labels
  serviceName: "sc-headless-svc" # this should be headless service
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        purpose: statefulset 
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  # this is nothing but pvc you can directy here
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi